apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: demo-pull-secret
  namespace: demo-pull-secret
spec:
  encryptedData:
    .dockerconfigjson: AgBZPwe9IBschEaOOaA9IVmRUpIWQTm1ujxSlLsh6sky6ipAy86yQDXcnE1VZKjlv2Xesn1YfEqlkpjkwc/Z0U0kkq6J0ZJtakKki45MfGhnCewua4a4/+YK9oqNzZYcQg5J6114NsUdqNyRx18tImta409s19Xi4x4xZ/83ZYcwlz+pmVzDujxcBUTOakoAOI49P23Y+gznyoVuvQyUmbc2bOJHCA1kvvImoL2d/ukonS7aKM5meKjl+J23ZAJeAgDIqVv/fAe64L9fVzVSXw8R3Miz/JffWLAKkj9lhjvUk452EO77im1/N+OgVgcv7GJudRUCi5oU52nkbHrGGzv2boHHwVt30jyOcPL9yI+GH9G/UkzT5MYcHPq6vOeNFoief00gj8DTsaYfhZ7+1CT0rVD2LL1h2Jxk0IKUyTaPBG1DfGRS02Sa2iKqh46nVVqq2bmp43ZqJipQncD5tNwTP3bkk/12to67GkhwWnvpJCKUDWVobiiLuq8EYueJ9QJbsS5bqsv+FbysURZO7BGJ8+RzxJNh2pl667ALvZMFz1sFkFmmz//M5wg4zi8ia2jnYeuewewXweGd9V5HHZef1He86JAjo+AQ6/Q4PVgVI+5e/Eyo5fU27zefH4wVbLZoDM/O8eLtcHiaT5UJ0Rge0Fh87ssbYvh4MpJYO4ryKu+7FPTPKbcQWl9JiYm/0Cfx/DzYD01cuyUuyeEHbPVTwjtOKGVo1WXC8t5sizkog5WWlCNp1NEnelRWS+8lj3nT65pp3T3YzMkghNfuo4pCZArg6Sx4owNwkPYZwyHp/jPFKQMO/8m/dmfhM0YtYd1ouoxGtp9Q9jlyPESwAgyhUAwGWaQ2di03ycw27vFIdAQ7Jdqff151y7BPpmtP4w5UBKFeIhv2iDQFjvJKD91gJMOJQXQx
  template:
    metadata:
      creationTimestamp: null
      name: demo-pull-secret
      namespace: demo-pull-secret
    type: kubernetes.io/dockerconfigjson

